package com.charity.report_service.service;

import com.charity.report_service.entity.Report;
import com.charity.report_service.entity.ReportData;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.layout.properties.VerticalAlignment;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfGeneratorService {

    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    // Color scheme
    private static final DeviceRgb PRIMARY_COLOR = new DeviceRgb(52, 73, 94);      // Dark blue
    private static final DeviceRgb SECONDARY_COLOR = new DeviceRgb(41, 128, 185);  // Blue
    private static final DeviceRgb ACCENT_COLOR = new DeviceRgb(46, 204, 113);     // Green
    private static final DeviceRgb LIGHT_GRAY = new DeviceRgb(236, 240, 241);      // Light gray
    private static final DeviceRgb HEADER_BG = new DeviceRgb(52, 152, 219);        // Header blue

    public byte[] generateReportPdf(Report report) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);

            // Set margins
            document.setMargins(40, 40, 40, 40);

            // ===== HEADER SECTION =====
            addHeader(document, report);

            // ===== REPORT INFORMATION SECTION =====
            addReportInfo(document, report);

            // ===== DESCRIPTION SECTION =====
            if (report.getDescription() != null && !report.getDescription().isEmpty()) {
                addDescription(document, report.getDescription());
            }

            // ===== PERIOD SECTION =====
            if (report.getPeriodStart() != null && report.getPeriodEnd() != null) {
                addPeriod(document, report);
            }

            // ===== REPORT DATA TABLE =====
            if (report.getReportData() != null && !report.getReportData().isEmpty()) {
                addReportDataTable(document, report);
            }

            // ===== FOOTER =====
            addFooter(document);

            document.close();
            return baos.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF: " + e.getMessage(), e);
        }
    }

    private void addHeader(Document document, Report report) {
        // Title with colored background
        Table headerTable = new Table(1);
        headerTable.setWidth(UnitValue.createPercentValue(100));

        Cell headerCell = new Cell()
                .add(new Paragraph(report.getTitle())
                        .setFontSize(24)
                        .setBold()
                        .setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(PRIMARY_COLOR)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(15)
                .setBorder(null);

        headerTable.addCell(headerCell);
        document.add(headerTable);
        document.add(new Paragraph("\n"));
    }

    private void addReportInfo(Document document, Report report) {
        // Section title
        Paragraph sectionTitle = new Paragraph("Report Information")
                .setFontSize(16)
                .setBold()
                .setFontColor(SECONDARY_COLOR)
                .setMarginBottom(10);
        document.add(sectionTitle);

        // Info table with 2 columns
        float[] columnWidths = {150f, 350f};
        Table infoTable = new Table(UnitValue.createPointArray(columnWidths));
        infoTable.setWidth(UnitValue.createPercentValue(100));

        // Add rows
        addInfoRow(infoTable, "Report ID:", String.valueOf(report.getId()));
        addInfoRow(infoTable, "Type:", report.getType().toString());
        addInfoRow(infoTable, "Status:", report.getStatus().toString());
        addInfoRow(infoTable, "Generated By:", report.getGeneratedBy());
        addInfoRow(infoTable, "Created Date:", report.getCreatedDate().format(formatter));
        addInfoRow(infoTable, "Updated Date:", report.getUpdatedDate().format(formatter));

        document.add(infoTable);
        document.add(new Paragraph("\n"));
    }

    private void addInfoRow(Table table, String label, String value) {
        // Label cell
        Cell labelCell = new Cell()
                .add(new Paragraph(label).setBold())
                .setBackgroundColor(LIGHT_GRAY)
                .setPadding(8)
                .setBorder(new SolidBorder(ColorConstants.WHITE, 1));

        // Value cell
        Cell valueCell = new Cell()
                .add(new Paragraph(value))
                .setPadding(8)
                .setBorder(new SolidBorder(ColorConstants.WHITE, 1));

        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private void addDescription(Document document, String description) {
        Paragraph sectionTitle = new Paragraph("Description")
                .setFontSize(16)
                .setBold()
                .setFontColor(SECONDARY_COLOR)
                .setMarginBottom(10);
        document.add(sectionTitle);

        // Description box
        Table descTable = new Table(1);
        descTable.setWidth(UnitValue.createPercentValue(100));

        Cell descCell = new Cell()
                .add(new Paragraph(description))
                .setPadding(15)
                .setBackgroundColor(LIGHT_GRAY)
                .setBorder(new SolidBorder(SECONDARY_COLOR, 1));

        descTable.addCell(descCell);
        document.add(descTable);
        document.add(new Paragraph("\n"));
    }

    private void addPeriod(Document document, Report report) {
        Paragraph sectionTitle = new Paragraph("Reporting Period")
                .setFontSize(16)
                .setBold()
                .setFontColor(SECONDARY_COLOR)
                .setMarginBottom(10);
        document.add(sectionTitle);

        Table periodTable = new Table(2);
        periodTable.setWidth(UnitValue.createPercentValue(100));

        // From
        Cell fromLabelCell = new Cell()
                .add(new Paragraph("From:").setBold())
                .setBackgroundColor(LIGHT_GRAY)
                .setPadding(8)
                .setTextAlignment(TextAlignment.CENTER);

        Cell fromValueCell = new Cell()
                .add(new Paragraph(report.getPeriodStart().format(formatter)))
                .setPadding(8)
                .setTextAlignment(TextAlignment.CENTER)
                .setBackgroundColor(ColorConstants.WHITE);

        // To
        Cell toLabelCell = new Cell()
                .add(new Paragraph("To:").setBold())
                .setBackgroundColor(LIGHT_GRAY)
                .setPadding(8)
                .setTextAlignment(TextAlignment.CENTER);

        Cell toValueCell = new Cell()
                .add(new Paragraph(report.getPeriodEnd().format(formatter)))
                .setPadding(8)
                .setTextAlignment(TextAlignment.CENTER)
                .setBackgroundColor(ColorConstants.WHITE);

        periodTable.addCell(fromLabelCell);
        periodTable.addCell(toLabelCell);
        periodTable.addCell(fromValueCell);
        periodTable.addCell(toValueCell);

        document.add(periodTable);
        document.add(new Paragraph("\n"));
    }

    private void addReportDataTable(Document document, Report report) {
        Paragraph sectionTitle = new Paragraph("Report Data")
                .setFontSize(16)
                .setBold()
                .setFontColor(SECONDARY_COLOR)
                .setMarginBottom(10);
        document.add(sectionTitle);

        float[] columnWidths = {200f, 200f, 100f};
        Table dataTable = new Table(UnitValue.createPointArray(columnWidths));
        dataTable.setWidth(UnitValue.createPercentValue(100));

        // Header row
        addTableHeader(dataTable, "Key");
        addTableHeader(dataTable, "Value");
        addTableHeader(dataTable, "Type");

        // Data rows with alternating colors
        boolean alternate = false;
        for (ReportData data : report.getReportData()) {
            DeviceRgb bgColor = alternate ? LIGHT_GRAY : (DeviceRgb) ColorConstants.WHITE;

            dataTable.addCell(createDataCell(data.getDataKey(), bgColor, true));
            dataTable.addCell(createDataCell(data.getDataValue(), bgColor, false));
            dataTable.addCell(createDataCell(data.getDataType(), bgColor, false));

            alternate = !alternate;
        }

        document.add(dataTable);
    }

    private void addTableHeader(Table table, String text) {
        Cell headerCell = new Cell()
                .add(new Paragraph(text).setBold().setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(HEADER_BG)
                .setPadding(10)
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE)
                .setBorder(new SolidBorder(ColorConstants.WHITE, 1));

        table.addHeaderCell(headerCell);
    }

    private Cell createDataCell(String text, DeviceRgb bgColor, boolean bold) {
        Paragraph p = new Paragraph(text);
        if (bold) p.setBold();

        return new Cell()
                .add(p)
                .setBackgroundColor(bgColor)
                .setPadding(8)
                .setBorder(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.5f));
    }

    private void addFooter(Document document) {
        document.add(new Paragraph("\n"));

        Paragraph footer = new Paragraph("Generated by Charity Report System - " +
                java.time.LocalDateTime.now().format(formatter))
                .setFontSize(10)
                .setFontColor(ColorConstants.GRAY)
                .setTextAlignment(TextAlignment.CENTER)
                .setItalic();

        document.add(footer);
    }
}