# ===============================
# Étape 1 : Construction du JAR
# ===============================
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# ===============================
# Étape 2 : Exécution de l'application
# ===============================
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8989
ENTRYPOINT ["java", "-jar", "app.jar"]
